#! /bin/sh
# www.github.com/mrcsbrn/dotfiles


###--- Inicialização ---###
cut -c3- $HOME/.config/sxhkd/sxhkdrc | sh -s _xmanager &
feh --bg-scale ~/.config/wall.jpg &
# Iniciar o polybar
cut -c3- $HOME/.config/sxhkd/sxhkdrc | sh -s _polybar_launcher &
nm-applet &
mpd &
transmission-daemon &
udiskie -2 -t &
xfce4-power-manager &
redshift-gtk &
dropbox start &
# Remove "system bell"
xset -b &
xset s off &
xset -dpms &
xset s noblank &
synclient VertScrollDelta=-100 &
# Configura layout do teclado; e 'concerta' o capslock
setxkbmap -model abnt2 -layout br -option 'caps:ctrl_modifier' &
xcape -e 'Caps_Lock=Escape' &
# Esconde cursor
unclutter --timeout 2 &
###--- Scripts shortcuts ---###
cut -c3- $HOME/.config/sxhkd/sxhkdrc | sh -s _compton_launcher &
# Script que sincroniza zshrc e ranger.rc
python $HOME/.scripts/syncaf.py &

sxhkd &
# bspwm config
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
